- name: BASE_OS | BASHPROFILE | Copy default .bash_profile
  copy:
    src=bash_profile
    dest="{{ item.home | default(['/home/',item.name] | join ) }}/.bash_profile"
    owner=root
    group=root
    mode=0644
  with_items:
    - "{{ ansible_centos_base__users }}"
  tags:
    - baseos
    - users
