---
# For users with sftp jail, we need to change permissions of the home folder 
# and create some dir so he will be able to save files.
# To set a hased password use: $# openssl passwd -salt SOMESALT -1 SOMEPASS

- name: BASE OS | USERS | Create jail basepath permissions
  file:
    path: "{{ ansible_centos_base__sshjaildir }}"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: BASE OS | USERS | Creating users
  user:
    name: "{{ item.name }}"
    #update_password: "{{ item.update_password | default('on_create') }}"
    state: "{{ item.state }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    home: "{{ item.home | default(['/home/',item.name] | join ) }}"
  with_items:
    - "{{ ansible_centos_base__users }}"

- name: BASE OS | USERS | Reset permission for jail users
  file:
    path: "{{ item.home }}"
    mode: 0755
    owner: root
    group: root
    state: directory
  with_items:
    - "{{ ansible_centos_base__users }}"
  when: 
    - item.jail == "yes"

- name: BASE OS | USERS | Set up authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_key }}"
    exclusive: True
  with_items:
    - "{{ ansible_centos_base__users }}"

