- name: BASE_OS | BASHPROFILE | Copy os-security.yml to apply security settings
  copy:
    src=bash_profile
    dest="{{ item }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - /root/.bash_profile
    - "/home/{{ ansible_centos_base__username }}/.bash_profile"


