- name: Copy os-security.yml to apply security settings
  copy:
    src=bash_profile
    dest="{{ item }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - /root/.bash_profile
    - /home/ansible/.bash_profile


