---
- name: HARDENING | KERNEL | Disable various kernel modules
  copy:
    content: "install {{ item }} /bin/false"
    dest: /etc/modprobe.d/{{ item }}.conf
  with_items:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - dccp
    - sctp
    - rds
    - tipc
    - firewire-core
    - usb-storage
    - net-pf-31
    - bluetooth
