---
- name: HARDENING | UMASK | Set default umask in {{ item.dest }}
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ umask_files }}"
