---
- name: Set up authorized_keys
  authorized_key: >
    user={{ ansible_centos_base__username }}
    key="{{ item }}"
    exclusive=True
  with_file:
    - ssh_keys

- name: Remove password SSH access
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication" 
    line="PasswordAuthentication no" 
    state=present
  notify: handler_restart_ssh
    
- name: Remove root ssh access
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin" 
    line="PermitRootLogin no" 
    state=present
  notify: handler_restart_ssh

