---
- name: Check authorized_keys before run
  fail:
    msg: "You need at least one authorized_key set on ansible_centos_base__authorized_keys "
  when: ansible_centos_base__authorized_keys is not defined

- name: Set up authorized_keys
  authorized_key: >
    user={{ ansible_centos_base__username }}
    key={{ ansible_centos_base__authorized_keys }}
    exclusive=True

- name: Remove password SSH access
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication" 
    line="PasswordAuthentication no" 
    state=present
  notify: handler_restart_ssh
    
- name: Remove root ssh access
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin" 
    line="PermitRootLogin no" 
    state=present
  notify: handler_restart_ssh

